name: Pipeline Testing

on:
  pull_request:
    branches:
      - main

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo 'Connection Succesful'

  test-utils:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and Clone Repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Test Utils
        run: npm run test-utils

  test-app:
    needs: test-utils
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and Clone Repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Setup Postgres
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: test_db
          postgresql user: MrNobody
          postgresql password: TESTPASS

      - name: Test App
        run: PGDATABASE=test_db PGUSER=MrNobody PGPASSWORD=TESTPASS npm run test-app

  test-live-app:
    needs: test-app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and Clone Repo
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Test Live App
        run: NODE_ENV=production DATABASE_URL=${{ secrets.DATABASE_URL }} npm run test-app
